# travis config, based on https://github.com/craigcitro/r-travis

language: c

script: ./travis-tool.sh run_tests

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
#  - ./travis-tool.sh github_package testthat
#  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh install_r_binary r.oo

branches:
  except:
   - /-expt$/

notifications:
  email:
    on_success: travis_report@aroma-project.org
    on_failure: travis_report@aroma-project.org

